spring:
  application:
    name: CricFlow
  datasource:
    url: jdbc:postgresql://localhost:5432/cricket_db
    username: postgres
    password: Postgres@28
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
       ddl-auto: create-drop
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true